# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml 
name: nf-core-circrnasponging
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - beautifulsoup4=4.10.0
  - bowtie=1.3.1
  - bwa=0.7.17
  - pandas=1.3.4
  - selenium=3.141.0
  - threadpoolctl=3.0.0
  - python=3.8.12
  # R packages
  - r-argparser=0.7.1
  - r-biocmanager=1.30.16
  - r-data.table=1.14.2
  - r-doparallel=1.0.16
  - r-dplyr=1.0.7
  - r-foreach=1.5.1
  - r-ggplot2=3.3.5
  - r-pheatmap=1.0.12
  - r-rcolorbrewer=1.1_2
  - r-reshape2=1.4.4
  - r-seqinr=4.2_8
  - r-stringr=1.4.0
  - r-tidyr=1.2.0
  - r-tidyselect=1.1.1
  - r-tidyverse=1.3.1
  - r-venndiagram=1.7.1
  - r-viridislite=0.4.0
  - r-visnetwork=2.1.0
  - bioconductor-sponge=1.16.0
  - bioconductor-annotate=1.72.0
  - bioconductor-annotationdbi=1.56.1
  - bioconductor-annotationfilter=1.18.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-biocparallel=1.28.0
  - bioconductor-biomart=2.50.0
  - bioconductor-biostrings=2.62.0
  - bioconductor-bsgenome=1.62.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-enhancedvolcano=1.12.0
  - bioconductor-ensembldb=2.18.1
  - bioconductor-genomeinfodb=1.30.0
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-genomicalignments=1.30.0
  - bioconductor-genomicranges=1.46.0
  - bioconductor-tximport=1.22.0
  # TarPmiR requirements
  - randfold=2.0.1
  - viennarna=2.4.18
  - scikit-learn==0.20.3
  - numpy==1.21.4
  - scipy==1.8.0
  # other  software
  - star=2.7.9a
  - miranda=3.3a
  - mirdeep2=2.0.1.3
  
